---

- name: Creating etcd user group
  group:
    name: "{{ etcd_group }}"

- name: Creating etcd user
  user:
    name: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "etcd nologin User"
    createhome: "no"
    state: present