---

- include: etcd_user.yml

- name: Ensure etcd directory exists
  file:
    dest: "{{ item }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    state: directory
  with_items:
    - "{{ etcd_install_dir }}"
    - "{{ etcd_data_dir }}"

- name: Download and extract etcd files
  unarchive:
    src: "{{ etcd_download_url }}"
    dest: "{{ etcd_install_dir }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    remote_src: yes
    extra_opts:
      - --strip=1
      - --wildcards
      - "etcd-v{{ etcd_version }}-linux-amd64/etcd*"

- name: Create symbolic link for etcd and etcdctl
  file:
    src: "{{ etcd_install_dir }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    state: link
  with_items:
    - etcd
    - etcdctl

- name: Create etcd service
  template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
  notify: etcd_reload